/**
 * HR.LeaveManagement.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LeaveTypeDetailsDto } from './leaveTypeDetailsDto';


export interface LeaveTypeDetailsDtoActionResult { 
    result?: object;
    value?: LeaveTypeDetailsDto;
}

