/**
 * HR.LeaveManagement.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateLeaveTypeCommand { 
    id?: number;
    name?: string | null;
    defaultDays?: number;
}

